name: Test and Lint

env:
  GITHUB_REFE: ${{ github.event.pull_request.base.ref == 'master' && github.ref || github.event.pull_request.head.sha }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - staging
      - master
jobs:
  js_test_and_lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REFE

