name: Test and Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - staging
      - master
jobs:
  js_test_and_lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - run: npm ci
      - run: echo hello

